#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-only

USE_PROCD=1
START=99

PROG=/usr/bin/dae

start_service() {
	config_load dae
	local enabled config_file
	config_get_bool enabled config enabled 0
	[ "$enabled" -eq 1 ] || return 0
	config_get config_file config config_file /etc/dae/config.dae
	"$PROG" validate -c "$config_file" || return 1

	procd_open_instance
	procd_set_param env DAE_LOCATION_ASSET=/usr/share/v2ray
	procd_set_param command "$PROG" run --config "$config_file" --disable-timestamp
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger dae
}

