#!/bin/sh
set -eu

role=
lan_mac=$(cat /sys/class/net/eth1/address 2>/dev/null || true)
case "$lan_mac" in
  02:00:00:00:a1:01) role=a ;;
  02:00:00:00:b1:01) role=b ;;
  *) exit 0 ;;
esac

if [ "$role" = a ]; then
  hostname=router-a
  lan_ip=10.81.0.1
  transit_ip=172.31.1.1
  transit_gateway=172.31.1.2
  remote_lan=10.82.0.0/24
else
  hostname=router-b
  lan_ip=10.82.0.1
  transit_ip=172.31.2.1
  transit_gateway=172.31.2.2
  remote_lan=10.81.0.0/24
fi

uci -q batch <<EOF
set system.@system[0].hostname='$hostname'

delete network.loopback
delete network.globals
delete network.lan
delete network.wan
delete network.wan6
set network.loopback='interface'
set network.loopback.device='lo'
set network.loopback.proto='static'
set network.loopback.ipaddr='127.0.0.1'
set network.loopback.netmask='255.0.0.0'
set network.globals='globals'
set network.globals.ula_prefix='auto'
set network.wan='interface'
set network.wan.device='eth0'
set network.wan.proto='dhcp'
set network.lan='interface'
set network.lan.device='eth1'
set network.lan.proto='static'
set network.lan.ipaddr='$lan_ip'
set network.lan.netmask='255.255.255.0'
set network.transit='interface'
set network.transit.device='eth2'
set network.transit.proto='static'
set network.transit.ipaddr='$transit_ip'
set network.transit.netmask='255.255.255.252'
set network.remote_lan='route'
set network.remote_lan.interface='transit'
set network.remote_lan.target='$remote_lan'
set network.remote_lan.gateway='$transit_gateway'
EOF

while uci -q delete firewall.@zone[0]; do :; done
while uci -q delete firewall.@forwarding[0]; do :; done
while uci -q delete firewall.@rule[0]; do :; done

uci -q batch <<'EOF'
set firewall.defaults='defaults'
set firewall.defaults.input='REJECT'
set firewall.defaults.output='ACCEPT'
set firewall.defaults.forward='REJECT'
set firewall.defaults.synflood_protect='1'

set firewall.lan='zone'
set firewall.lan.name='lan'
set firewall.lan.network='lan'
set firewall.lan.input='ACCEPT'
set firewall.lan.output='ACCEPT'
set firewall.lan.forward='REJECT'

set firewall.wan='zone'
set firewall.wan.name='wan'
set firewall.wan.network='wan'
set firewall.wan.input='REJECT'
set firewall.wan.output='ACCEPT'
set firewall.wan.forward='REJECT'
set firewall.wan.masq='1'
set firewall.wan.mtu_fix='1'

set firewall.transit='zone'
set firewall.transit.name='transit'
set firewall.transit.network='transit'
set firewall.transit.input='ACCEPT'
set firewall.transit.output='ACCEPT'
set firewall.transit.forward='REJECT'

set firewall.site_out='forwarding'
set firewall.site_out.src='lan'
set firewall.site_out.dest='transit'

set firewall.site_ping='rule'
set firewall.site_ping.name='Permit inter-site ICMP'
set firewall.site_ping.src='transit'
set firewall.site_ping.dest='lan'
set firewall.site_ping.proto='icmp'
set firewall.site_ping.target='ACCEPT'

set firewall.site_web='rule'
set firewall.site_web.name='Permit inter-site learning web service'
set firewall.site_web.src='transit'
set firewall.site_web.dest='lan'
set firewall.site_web.proto='tcp'
set firewall.site_web.dest_port='8080'
set firewall.site_web.target='ACCEPT'

set firewall.luci_lab='rule'
set firewall.luci_lab.name='Permit LuCI from QEMU loopback forward'
set firewall.luci_lab.src='wan'
set firewall.luci_lab.proto='tcp'
set firewall.luci_lab.dest_port='443'
set firewall.luci_lab.target='ACCEPT'
EOF

uci commit system
uci commit network
uci commit firewall
printf '%s\n' "$role" > /etc/oslab-role
exit 0

